env:
  global:
    - GH_REPO="makotot/performance-notes"
    - GIT_COMMITTER_NAME=makotot
    - GIT_COMMITTER_EMAIL=makoto.ttn@gmail.com
    - GIT_AUTHOR_NAME=makotot
    - GIT_AUTHOR_EMAIL=makoto.ttn@gmail.com
    - secure: avQKZeUFgW+FyRnh3hyZKzcTzrTEHwOO0AFmOD4agrcsuJoIS2MSp3KGaK/gy2GujPJXhuLFETQnN0adXZMxQ9TdpJ2AsPUvZthP3L0V+6T07EsDIy/rAG0YykH849saYefmZEkiAuTDnn5NgrjfkysYZUvyPpPaBD2J1WRHojc=

language: node_js

node_js:
  - 0.10

branches:
  only:
    - master

before_script:
  - npm install -g gulp

script:
  - gulp ci --type production

after_success:
  - ./deploy.sh

